name: noindex-checker
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-python
  name: sample-python
  build:
      # Add the following two lines
      env:
        PIP_REQUIREMENTS: requirements.txt
